language: node_js
dist: trusty
node_js:
  - "8"
install:
  - npm install
script:
  - hexo clean
  - \cp -f README.md source\_posts\README.md
  - hexo g
  - chmod +x ./deploy.sh
  - \cp -f assets/CNAME public/CNAME
  # - \cp -f assets/.nojekyll /.nojekyll
  - ./deploy.sh > /dev/null
  - hexo clean
cache:
  directories:
    - node_modules
branches:
  only:
    - master